$options = {
  :version => "RuMuBo 0.6",                          # Name of the Client
  :debug => false,                                   # debug output (can be overriden on the console)
  :country_code => "CH",                             # Autogenerated Certificates: Country
  :organisation => "Apophis.ch",                     # Autogenereted Certicicates: Organisation
  :organisation_unit => "Software",                  # Autogenereted Certicicates: Organisation
}

# Servers with their Master Bots

$servers = []
$servers << { :host => "apophis.ch", :port => 64738, :channel => "International Bridge", :nick => "bridge-master" }
$servers << { :host => "talk.piratenpartei.ch", :port => 64738, :channel => "International Bridge", :nick => "bridge-master" }



